# Generated by Django 5.2.4 on 2025-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('FREE', '자유'), ('travel', '여행'), ('cat', '고양이'), ('dog', '강아지')], max_length=10, verbose_name='카테고리'),
        ),
    ]
