# Generated by Django 5.2.5 on 2025-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='영업 시작')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='영업 마감')),
                ('last_order', models.TimeField(blank=True, null=True, verbose_name='마지막 주문')),
                ('regular_holiday', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10, null=True, verbose_name='휴무')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
