# Generated by Django 5.2.4 on 2025-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/completed', verbose_name='완료 이미지'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='image/completed_default.png', null=True, upload_to='image/completed/thumbnail', verbose_name='썸네일'),
        ),
    ]
